---
- name: Teleport | Reset teleport
  file:
    path: "{{ teleport_data_dir }}/"
    state: absent
  when: teleport_reset

- name: Teleport | Check if teleport is installed
  stat:
    path: /usr/local/bin/teleport
  register: teleport_bin

- name: Teleport | Download teleport archive file
  get_url:
    url: "{{ teleport_binary_url }}/teleport-v{{ teleport_version }}-linux-amd64-bin.tar.gz"
    dest: /tmp/teleport-v{{ teleport_version }}-linux-amd64-bin.tar.gz
  when: not teleport_bin.stat.exists

- name: Teleport | Unarchive teleport archive file
  unarchive:
    src: /tmp/teleport-v{{ teleport_version }}-linux-amd64-bin.tar.gz
    dest: /tmp
    remote_src: true
  when: not teleport_bin.stat.exists

- name: Teleport | Install teleport
  command: |
    make install
  args:
    chdir: /tmp/teleport
  when: not teleport_bin.stat.exists

- name: Teleport | Add teleport config file
  template:
    src: teleport.yaml.j2
    dest: /etc/teleport.yaml
    owner: root
    group: root
    mode: 0644
  register: teleport_conf

- name: Teleport | Add teleport systemd file
  template:
    src: teleport.service.j2
    dest: /usr/lib/systemd/system/teleport.service
    owner: root
    group: root
    mode: 0644
  register: teleport_systemd_conf

- name: Teleport | Restart teleport
  systemd:
    name: teleport
    state: restarted
    daemon_reload: true
  when: teleport_conf.changed or teleport_systemd_conf.changed

- name: Teleport | Start and Enable teleport
  systemd:
    name: teleport
    state: started
    enabled: true
